version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:cached
      - ./docker/base/clock:/etc/sysconfig/clock
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/localhost.pem:/etc/ssl/certs/localhost.pem
      - ./docker/nginx/localhost-key.pem:/etc/ssl/certs/localhost-key.pem
      - ./docker/php/php-fpm/www.conf:/etc/opt/remi/php81/php-fpm.conf
      - ./docker/php/php.ini:/etc/php.ini
      - ./docker/php/xdebug.ini:/etc/php.d/xdebug.ini
    privileged: true
    ports:
      - "10081:80"
      - "10443:443"
    working_dir: /var/www/html
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravue
      MYSQL_USER: laravue
      MYSQL_PASSWORD: laravue
      MYSQL_ROOT_PASSWORD: laravue
    ports:
      - "14306:3306"
    volumes:
      - laravue_db:/var/lib/mysql
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - laravue_redis:/data
volumes:
  laravue_db:
    driver: local
  laravue_redis: